// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type TbTask struct {
	ID          int64
	Title       string
	IsCompleted bool
	CreatedAt   time.Time
	CompletedAt sql.NullTime
}
