// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type TbTodo struct {
	ID          sql.NullInt64
	Title       string
	Status      sql.NullInt64
	CreatedAt   sql.NullTime
	ModifiedAt  sql.NullTime
	CompletedAt sql.NullTime
}
